# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Path-Class-File-Stat
version:      0.01
version_from: lib/Path/Class/File/Stat.pm
installdirs:  site
requires:
    Path::Class:                   0.15

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
