--- #YAML:1.0
name:               Path-Class-File-Stat
version:            0.03
abstract:           cache and compare stat() calls on a Path::Class::File object
author:
    - Peter Karman <karpet@peknet.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Path::Class:  0.15
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
